config/routes.rb
Rails.application.routes.draw do
  # devise設定時点でルーティングが自動的に追加されています。
  # devise_for :usersは、deviseを使用する際にURLとしてusersを含むことを示しています。
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # deviseでは、ログイン認証が成功した場合、config/routes.rbファイル内で設定されているrootパスへリダイレクトされます。
  # 下記未記入ではrootパスが設定されていないため、初期設定の「Yay! You’re on Rails!」画面へリダイレクトされます。
  # ログイン認証が成功した後、投稿画像の一覧画面が表示されるように設定します。
  root 'post_images#index'
  # resources :リソース名, only:(オプション) [:new, :create, :index, :show](のアクションのルートだけ作る)
  # onlyは、生成するルーティングを限定するオプションです。
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do # コメントは、投稿画像に対してコメントされます。このため、post_commentsは、post_imagesに結びつきます。
  	resource :favorites, only: [:create, :destroy]# resourceなのは単数にすると、そのコントローラのidがリクエストに含まれなくなります。
  	resource :post_comments, only: [:create, :destroy]# post_commentsのshowページが不要で、idの受け渡しも必要ないので、resourceとなっています。
  end# doの後にはend
  resources :users, only: [:show, :edit, :update]# マイページ作成、編集可能
end# doの後にはend

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	# Favoriteモデルに関連付けを追加する
	belongs_to :user
	belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	# UserモデルとPostCommentモデルを関連付ける。親＝参照される側、子＝参照する側
	belongs_to :user# 親：user、子：post_comment
    belongs_to :post_image# 親：post_image、子：post_comment
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	# has_manyとは逆の機能になります。
	# belongs_toは、PostImageモデルからuser_idに関連付けられていて、Userモデルを参照することができます。
	# PostImageモデルに関連付けられるのは、1つのUserモデルです。このため、単数形の「user」になっている点に注意しましょう。
	belongs_to :user
	# 画像アップロードは、%= f.attachment_field :image %で実装しています。
	# 以下の2つは、refileを使用するうえでのルールです。
		# 指定するフィールド名は、image_idから_idを除いた名前（image）を指定します。
		# また、モデルにも、画像アップ用のメソッド（attachment_field）を追加します。
	attachment :image # ここを追加（_idは含めません）
	# PostImageモデルとPostCommentモデルを関連付ける
	# has_many(参照される側)の後には、1:Nの関係になるモデル名を複数形で記述します。has_manyでPostCommentモデルを複数持つことを表しています。
	has_many :post_comments, dependent: :destroy# dependent=従属関係の
	# PostImageモデルに関連付けを追加する
	# favorited_by?メソッドを作成します。このメソッドで、引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べます。
	# 存在していればtrue、存在していなければfalseを返すようにしています。
	has_many :favorites, dependent: :destroy
	# 今回、画像投稿に対して「必須入力」の設定が必要なので、PostImageモデルにデータ保存の記述を追加します。
	# validatesで対象とする項目を指定し、入力されたデータのpresence（存在）をチェックします。データが入っていれば、trueです。
	validates :shop_name, presence: true# presence=存在
    validates :image, presence: true
        def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise設定時点でuser.rbファイルも自動作成され、Userモデルが定義されています。
  # このモデルには、deviseで利用する機能が記述されています。
	# 「:database_authenticatable, :registerable,」のように、deviseの後ろに :（コロン）で始まる部分がdeviseの機能名です。
	# :database_authenticatable（パスワードの正確性を検証）
	# :registerable（ユーザ登録や編集、削除）
	# :recoverable（パスワードをリセット）
	# :rememberable（ログイン情報を保存）
	# :validatable（emailのフォーマットなどのバリデーション）
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Userモデルに対して、PostImageモデルが1:Nになるよう関連付けます。
  # has_many(参照される側)の後には、1:Nの関係になるモデル名を複数形で記述します。
  has_many :post_images, dependent: :destroy# dependent=従属関係の
  # Userモデルに、PostImageモデルとの関連付けを記述します。PostCommentモデルとの1:Nの関係も実装します。
  has_many :post_comments, dependent: :destroy
  # Favoriteモデルのカラム（user_idとpost_image_id）は、UserモデルのidやPostImageモデルのidと関連付けが必要です。
  has_many :favorites, dependent: :destroy
  # 以下の2つは、refileを使用するうえでのルールです。（画像投稿機能）
	# 指定するフィールド名は、profile_image_idから_idを除いた名前（profile_image）を指定します。
	# また、モデルにも、画像アップ用のメソッド（attachment_field）を追加します。
  attachment :profile_image# refileを使って、画像投稿ができるようにします。その際、refile特有の記述ルールに注意しましょう。（id不要）
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Meshiterroでは、ログイン認証が成功していないと、どの画面も表示できない仕様にしたいと思います。
	# before_actionメソッドは、このコントローラが動作する前に実行されます。
	# 今回の場合、app/controllers/application_controller.rbファイルに記述したので、すべてのコントローラで、最初にbefore_actionメソッドが実行されます。
	# authenticate_userメソッドは、devise側が用意しているメソッドです。
	# :authenticate_user!とすることによって、「ログイン認証されていなければ、ログイン画面へリダイレクトする」機能を実装できます。
	before_action :authenticate_user!
	# 今回は、初期設定では用意されていないカラム（name）を追加しているので、これを追記します。
    before_action :configure_permitted_parameters, if: :devise_controller?
    # private:クラス内のみアクセス可能(自分のコントローラ内でしか参照できません)
    # protected:クラス内、同一パッケージ、サブクラスからアクセス可(呼び出された他のコントローラからも参照できます)
  	protected
	def configure_permitted_parameters
		# .permitメソッドで変更を加えられる（保存の処理ができる）キーを指定します。(検索、比較、整列（並べ替え）などに用いられるデータのことをキーということがある。)
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])# permit=許可
 	end

end

Refile.secret_key = '4e434f3dac197227ca0e8ce53f8de0ce7027082ffcac0b967e72301439286af60428f672e9fc60e1a756153cf22f9e2cf701d7b3d40887925b6ab2939ed2d646'

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	# いいね機能も、indexアクションやnewアクションは作成しません。
	# コメント機能同様、投稿画像の詳細画面（/post_image/:id/）で実装します。
		def create
            post_image = PostImage.find(params[:post_image_id])
            favorite = current_user.favorites.new(post_image_id: post_image.id)# 省略形
            favorite.save
            redirect_to post_image_path(post_image)
        end
        def destroy
            post_image = PostImage.find(params[:post_image_id])
            favorite = current_user.favorites.find_by(post_image_id: post_image.id)# 省略形
            favorite.destroy
            redirect_to post_image_path(post_image)
        end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	# 今回、indexアクションやnewアクションは作成しません。
	# つまり、コメント投稿だけの一覧画面や投稿画面は作成せず、その代わり、投稿画像の詳細画面（/post_image/:id/）にコメント投稿機能を実装します。
	def create
	end
	def show # 2 詳細
		
	end
	def create # 5 保存 コメント投稿機能を作成する
		post_image = PostImage.find(params[:post_image_id])
		# comment = PostComment.new(post_comment_params)<br>comment.user_id = current_user.idの省略記述
	    comment = current_user.post_comments.new(post_comment_params)# 現在のuserがコメントすると初期値のコメントが作られその中に引数（投稿した内容）が反映され、それがcommentと定義されている？
	    comment.post_image_id = post_image.id# comment.post_image_id(コメントのid) と post_image.id(ユーザーのid)が一致していたらsave
	    comment.save
	    redirect_to post_image_path(post_image)# post_images#show
	end
	private
	def post_comment_params
	    params.require(:post_comment).permit(:comment)
	end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
# 画像の投稿画面を表示する
	def new
		@post_image = PostImage.new# 1.空のインスタンスを渡して、画像の投稿ができるようにします。
    end
# 投稿画像を保存する
    def create
    	# 9,10行目統合可能has manyのおかげ=>@post_image = PostImage.current_user.id.new(post_image_params)???わからん省略系の記述の方がメジャー
    	@post_image = PostImage.new(post_image_params)# 2.投稿データを保存する。投稿データを保存するには、Strong Parametersも必要なので、同時に定義
    	@post_image.user_id = current_user.id# current=現在の @post_image.user.idは現在のuser.idと一致した場合save
    	if @post_image.save
          redirect_to post_images_path# saveメソッドの結果がtrueならば、images#indexにリダイレクトさせます。
        else
          render :new# 画像投稿ページを再表示するように設定します。post_images#new
        end
    end
# 投稿画像のリストを表示する画面を作る
    def index# reverse_order=降順に取得したい場合
    	@post_images = PostImage.page(params[:page]).reverse_order# 3.postimagesテーブル内の全データが取得されていました。これを、1ページ分の決められた数のデータだけを、新しい順に取得するように変更しています。
    end
# 投稿画像の詳細を表示する画面を作る
    def show
    	@post_image = PostImage.find(params[:id])# idを持った@インスタンス変数
		@post_comment = PostComment.new# 空のインスタンス変数作成
    end

# 投稿画像削除機能
	def destroy # 7 削除
		@post_image = PostImage.find(params[:id])
    	@post_image.destroy# 取得した投稿を削除
    	redirect_to post_images_path# 投稿画面へリダイレクト
	end

	private
		def post_image_params
			params.require(:post_image).permit(:shop_name, :image, :caption)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show# マイページ作成
  	@user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page]).reverse_order  # そのユーザ（@user）に関連付けられた投稿（.post_images）のみ、@post_imagesに渡すことができます。late順
  end
  # プロフィール編集用
  def edit
    @user = User.find(params[:id])# params[:id]でユーザの情報を取得してインスタンス（@user）に保存し、編集用Viewでform_forを使う準備をしています。
  end

  def update # 6 更新
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!-- 共通するレイアウト ヘッダー フッターなど -->
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meshiterro</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head> 

  <body>
<!-- 3行目～21行目、% if user_signed_in? %>……% else %>……% end %>までが、ユーザのログイン状態によって表示を変更している条件分岐文です。 -->
    <div class="header" id="header">
      <nav class="navbar navbar-main navbar-shadow" role="navigation" id="slide-nav">
        <div class="container relative">
          <div class="navbar-header">
            <a class="navbar-logo" href="/">
              <%= image_tag('logo.png') %>
            </a>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="slidemenu">
            <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
              <!-- user_signed_inは、devise側で用意しているヘルパーです。ログイン済みならば、trueが返されます。 -->
              <% if user_signed_in? %>
                <li class="">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
                <li class="">
                  <%= link_to '投稿フォーム', new_post_image_path %>
                </li>
                <!-- マイページへのリンク -->
                <li class="">
                  <%= link_to 'マイページ', user_path(current_user.id) %>
                </li>
              <% else %>
                <li class="">
                  <%= link_to "新規登録", new_user_registration_path %>
                </li>
                <li class="">
                  <%= link_to "ログイン", new_user_session_path %>
                </li>
              <% end %>
            </ul>
        </div>
      </nav>
    </div>
    <!-- yieldという英単語を日本語に訳すと「産する、もたらす、生む、引き起こす」など、いろいろな意味があります。 -->
    <!-- Rubyにおけるyieldの意味としてしっくりくるのは「他のものに取って代わられる」でしょう。 -->
    <!-- 一般的にRubyのメソッド引数には、数値や文字列など単体のオブジェクトを渡すこともできるのですが、実はブロックというものを渡すこともできます。 -->
    <!-- ブロックとは「メソッド呼び出しの際に引数と一緒に渡すことのできる処理のかたまり」です。 -->
    <!-- yieldは「渡されているブロックと同じ働きをするメソッドのようなもの」とも言えるでしょう。 -->
    <!-- rubyではすべてのメソッドがデフォルトでブロック引数を受け取れるようになっています。 -->
    <!-- だから、特になにも引数に指定しなくてもブロックを渡すことができたのです。 -->
    <%= yield %>

   <footer class="footer style-2">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="col">
              <br>
              <p class="no-margin" style="font-size: 11px;">
              <br>
              善良な市民同士で無差別に食欲を煽るSNS
          </p>
              <%= image_tag('logo-white.png') %>
              
            </div>
          </div>
          <div class="col-md-2">
            <div class="col">
              <h4>Link</h4>
              <ul>
                <li>
                  <a href="" title="About">会社概要</a>
                </li>
                <li>
                  <a href="" title="License informations">プライバシーポリシー</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
</html>

app/views/post_images/_list.html.erb
<!-- 部分テンプレートファイル -->

<section class="sct-color-1 slice">
  <div class="container-fluid masonry-container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2">
        <div class="masonry-wrapper-cols">

          <div class="masonry-gutter"></div>

          <!-- （showの場合は）コントローラから渡されたpost_images変数内から1つずつ取り出して、post_image変数へ格納します。 -->
            <!-- 部分テンプレート用にコードを変更する。 -->
            <!-- 部分テンプレートファイル内でインスタンス変数を利用すると、同じ名前の「アクション」からしか呼び出せなくなってしまいます。これでは、再利用しにくいテンプレートになってしまいますね。 -->
            <!-- 部分テンプレートが呼び出されたときに、Viewから渡される変数が使えるように変更します。この変数には、ローカル変数を使います。 -->
            <% post_images.each do |post_image| %>
            <div class="masonry-block">
              <div class="block block-image v1">
                <div class="block-image">
                  <div class="view view-first">
                    <!-- attachment_image_tagは、refile側が用意したヘルパーで、<img>タグを作成してくれます。 -->
                    <!-- post_image変数のimage_idに保存された画像の<img>タグを生成します。 -->
                    <%= link_to post_image_path(post_image.id) do %>
                    <!-- post_image変数のshop_nameカラムを表示します。 -->
                    <!-- このカラムは、post_imageモデルに定義されています。 -->
                      <%= attachment_image_tag post_image, :image %>
                    <% end %>
                  </div>
                </div>
                <div class="block-content">
                  <!-- 投稿に表示されるユーザ画像も、プロフィール画像に変更します。 -->
                  <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
                  <h3 class="block-title">
                    <%= link_to post_image_path(post_image.id) do %>
                      <i class="fa fa-map-marker"></i><%= post_image.shop_name %>
                    <% end %>
                  </h3>
                  <!-- post_image変数のcaptionカラムを表示します。 -->
                  <!-- このカラムも、post_imageモデルに定義されています。 -->
                  <p><%= post_image.caption %></p>
                  <!-- コメント件数の表示を記述する -->
                  <ul class="inline-meta">
                    <li>By
                      <%= post_image.user.name %>
                    </li>
                    <li>
                      <%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id) %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <% end %>
            <%= paginate post_images, class: "pagenate" %><!-- @post_images → post_images -->

        </div>
      </div>
    </div>
  </div>
</section>

app/views/post_images/index.html.erb
<!-- postimageのindex画面 -->
<!-- post_images/index.html.erbから呼び出す -->
<%= render 'post_images/list', post_images: @post_images %>

app/views/post_images/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>画像投稿フォーム</span>
              </h3>
            </div>

            <!-- errorsは、モデルにバリデーションをかけたときに、発生したエラーの内容を確認できるメソッドです。 -->
            <!-- エラー文は配列で保存されているため、eachを使います。 -->
            <!-- <form class="mt-20"> -->
            <%= form_for(@post_image, url: post_images_path) do |f| %>
            <!-- any?と組み合わせることで、エラーが発生しているかどうかを判定できます。 -->
              <% if @post_image.errors.any? %>
                <div id="error_explanation">
                  <h2><%= @post_image.errors.count %>件のエラーが発生しました。</h2>
                  <ul>
                  <% @post_image.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.attachment_field :image %>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">ショップ名</label>
                    <%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
                </div>
              </div>
              <hr>
              <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
            <% end %>
            <!-- </form> -->

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/post_images/show.html.erb
<section class="sct-color-1 slice">
  <div class="container">
    <div class="row">
      <div class="col-md-12 post_images_container">
        <div class="post-item">

         <div class="post-meta-top">
           <div class="post-image">
             <%= attachment_image_tag @post_image, :image %>
           </div>
         </div>
        <div class="post-content">
            <h2 class="post-title"><%= @post_image.shop_name %></h2>
            <ul class="meta-info-cells v4 float-wrapper">
              <li>
                 <i class="fa fa-user"></i>By<a href="#">
                 <%= @post_image.user.name %></a>
              </li>
              <li>
                <!-- '%Y/%m/%d'の記述で、年/月/日のフォーマットへ変換します。 -->
                <!-- %Y、%m、%dは、日時のフォーマット指定によく使われます。覚えておきましょう。 -->
                <i class="fa fa-calendar"></i><%= @post_image.created_at.strftime('%Y/%m/%d') %>
              </li>
              <!-- favorited -->
              <!-- 投稿画像に付けられた「いいね」に、自分（ログインしているユーザ）が含まれているかをfavorited_by?メソッドで判定しています。 -->
              <% if @post_image.favorited_by?(current_user) %>
                <li>
                  <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
                    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                    <%= @post_image.favorites.count %> いいね
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to post_image_favorites_path(@post_image), method: :post do %>
                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                    <%= @post_image.favorites.count %> いいね
                  <% end %>
                </li>
              <% end %>
              <li>
                <!-- 投稿画像へのコメント -->
                <i class="fa fa-comment"></i>
                <a href="#comments"><%= @post_image.post_comments.count %></a>
              </li>
              <!-- 削除ボタン設置 -->
              <li>
                <!-- もし、投稿者 == 現在ログインしているユーザだったら 削除ボタン 終わり -->
                <% if @post_image.user == current_user %>
                  <%= link_to "削除", post_image_path(@post_image), method: :delete %>
                <% end %>
              </li>
            </ul>
            <div class="post-content-inner mt-20">
                <p><%= @post_image.caption %></p>
            </div>
        </div>
          <!-- コメント数も表示 -->
          <div class="comment-list bt style-2" id="comments">
            <div class="float-wrapper">
              <h2 class="comment-count"><%= @post_image.post_comments.count %>件コメント</h2>
            </div>
            <ol>
              <!-- コメント本文の表示を変更する -->
              <% @post_image.post_comments.each do |post_comment| %>
                <li class="comment">
                    <div class="comment-body bb">
                        <div class="comment-avatar">
                            <div class="avatar">
                                <!-- プロフィール画像を反映させる -->
                                <%= attachment_image_tag post_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                            </div>
                        </div>
                        <div class="comment-text">
                            <div class="comment-author clearfix">
                                <a href="#" class="link-author"><%= post_comment.user.name %></a>
                                <span class="comment-meta">
                                  <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
                                </span>
                            </div>
                            <div class="comment-entry"><%= post_comment.comment %></div>
                        </div>
                    </div>
                </li>
            <% end %>
            </ol>
          </div>
          <hr>

          <!-- Add comment section -->
          <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
            <h3 class="section-title left">
              <span>コメント</span>
            </h3>
          </div>
            <!-- コメント入力フォームを記述する -->
            <!-- form_forに対して、[@post_image,@post_comment]のように、配列でインスタンス変数を2つ指定している点に注意してください。 -->
            <!-- コメントは、post_imageに結びついたpost_commentにあるため、2つ用意する必要があります。 -->
            <!-- また、post_commentをcreateするためのリクエストは、ルーティングもネスト（親子関係）しているため、上記2つの情報が必要になります。 -->
            <%= form_for [@post_image, @post_comment] do |f| %>
              <div class="row">
                  <div class="col-sm-12">
                      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                  </div>
              </div>
              <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
            <% end %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<!-- usersのedit（プロフィール編集機能） -->
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">
          <section class="slice slice-lg sct-color-1">
              <div class="container">
                  <div class="row">
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-user style-1 rounded has-shadow-1">
                            <div class="form-header text-center">
                                <h2 class="form-header-title">プロフィール編集</h2>
                            </div>
                    <div class="form-body">
                    <!-- form_forを挿入して、投稿画像を編集できるようにします。 -->
                    <%= form_for(@user) do |f| %><!-- form_forでは、さきほどのインスタンス（editアクションの@user）を使います。 -->
								    <div class="form-group has-icon">
								        <label class="control-label sr-only" for="inputEmail">Name</label>
								        <!-- text_fieldで、nameカラムを変更できるようにしています。 -->
								        <!-- 紫字はhtmlの属性？ -->
								        <!-- autofocus:ページがロードされた時に、ユーザーIDや検索ワードなどの入力フィールドに自動的にフォーカスさせる -->
								        <!-- placeholder:フォームにあらかじめ薄いテキストで「佐藤 太郎」のように記入 -->
								        <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
								        <span class="fa fa-user form-control-icon" aria-hidden="true"></span><!-- aria-hidden="true"で何してるの？ -->
								    </div>
                    <div class="form-group has-icon">
                      <div class="user-edit-image">
                          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                      </div>
                      <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
                      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
                    </div>
								    <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
							      <% end %>
                            </div>
                          </div>
                      </div>
                  </div>
              </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- usersのshow（マイページ画面） -->
<!-- 最後に、ユーザのプロフィールを、ページ上部に記述します。これでマイページのがわ完成です。 -->
<div class="profile-container">
    <h3 class="profile-name"><%= @user.name %></h3>
    <!-- 3行目の記述をattachment_image_tag……に変更し、プロフィール画像が表示できるようにしています(refile) -->
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
    <% if @user.id == current_user.id %>
        <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right" %></p>
    <% end %>
</div>
<%= render 'post_images/list', post_images: @post_images %>